"use client";

import { useState, useEffect } from "react";
import { ShieldCheck, Download, Loader2 } from "lucide-react";
import { getToken } from '../../sign-in/auth';
import { useToast } from "@/context/ToastContext";

export default function CpcbComplianceView() {
  const { showToast } = useToast();
  const [logs, setLogs] = useState<any[]>([]);
  const [totalWeight, setTotalWeight] = useState(0);
  const [loading, setLoading] = useState(true);

  const handleDownloadReceipt = (e: React.MouseEvent, log: any) => {
    e.preventDefault();
    e.stopPropagation();
    
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <title>CPCB Form-2 Receipt - ${log.id}</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; background: #f8fafc; color: #0f172a; margin: 0; }
        .container { max-w-7xl; margin: 0 auto; background: white; padding: 50px; border-radius: 12px; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1); border: 1px solid #e2e8f0; }
        .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #10b981; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { margin: 0; color: #10b981; font-size: 24px; font-weight: 800; text-transform: uppercase; letter-spacing: 1px; }
        .header p { margin: 4px 0 0 0; color: #64748b; font-size: 14px; font-weight: 600; }
        .seal { font-size: 12px; font-weight: 700; color: #10b981; border: 2px solid #10b981; padding: 8px 12px; border-radius: 6px; text-transform: uppercase; }
        .table { w-full; border-collapse: collapse; margin-bottom: 40px; width: 100%; }
        .table th { text-align: left; padding: 16px; background: #f8fafc; color: #64748b; font-size: 12px; font-weight: 700; text-transform: uppercase; border-bottom: 2px solid #e2e8f0; }
        .table td { padding: 16px; font-size: 15px; color: #334155; font-weight: 600; border-bottom: 1px solid #f1f5f9; }
        .status { display: inline-block; padding: 6px 12px; background: #ecfdf5; color: #059669; border-radius: 20px; font-size: 12px; font-weight: 800; text-transform: uppercase; }
        .footer { text-align: center; color: #94a3b8; font-size: 12px; font-weight: 500; margin-top: 40px; padding-top: 20px; border-top: 1px dashed #cbd5e1; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div>
                <h1>Form-2 Compliance Certificate</h1>
                <p>E-Waste (Management) Rules, 2022 Registration</p>
                <p>Receipt ID: ${log.id}</p>
            </div>
            <div class="seal">Verifiably Recycled</div>
        </div>
        
        <table class="table">
            <tbody>
                <tr><th>CPCB Equipment Code</th><td>${log.code}</td></tr>
                <tr><th>Equipment Description</th><td>${log.desc}</td></tr>
                <tr><th>Date Processed</th><td>${log.date}</td></tr>
                <tr><th>Collection Source</th><td>${log.source}</td></tr>
                <tr><th>Quantity (Units)</th><td>${log.qty} Units</td></tr>
                <tr><th>Total Weight (KG)</th><td><span style="color: #059669; font-weight: 800;">${(log.weight ?? 0).toFixed(1)} KG</span></td></tr>
                <tr><th>Compliance Status</th><td><span class="status">${log.status}</span></td></tr>
            </tbody>
        </table>
        
        <div class="footer">
            Generated by Authorized Intermediary Portal on ${new Date().toLocaleString()}<br/>
            This document serves as an official processing record for CPCB auditing.
        </div>
    </div>
</body>
</html>
`.trim();

    const blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.style.display = "none";
    link.href = url;
    link.download = `Form2_Receipt_${log.id.replace(/[^a-zA-Z0-9]/g, '_')}.html`;
    
    document.body.appendChild(link);
    link.click();
    
    setTimeout(() => {
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
    }, 100);
    
    showToast(`Receipt Generated\nForm-2 Receipt for ${log.id} has been downloaded.`, 'success');
  };

  useEffect(() => {
    async function fetchData() {
      try {
        const token = getToken();
        const headers: HeadersInit = {};
        if (token) headers["Authorization"] = `Bearer ${token}`;

        const response = await fetch('/api/v1/reports/export/compliance', { headers });
        const json = await response.json();
        if (json.success) {
          setLogs(json.logs);
          setTotalWeight(json.totalWeight);
        }
      } catch (error) {
        console.error("Failed to fetch compliance view data:", error);
      } finally {
        setLoading(false);
      }
    }
    fetchData();
  }, []);

  if (loading) {
    return (
      <div className="flex items-center justify-center p-20 min-h-[400px]">
        <Loader2 className="animate-spin text-emerald-500 w-10 h-10" />
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-6 mt-4">
      
      {/* Alert Banner */}
      <div className="bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-100 rounded-3xl p-6 shadow-sm flex items-start sm:items-center gap-5">
        <div className="p-3 bg-blue-100 text-blue-700 rounded-2xl flex-shrink-0">
          <ShieldCheck size={28} />
        </div>
        <div className="flex-1">
          <h3 className="text-lg font-bold text-gray-900 tracking-tight">CPCB Form-6 Alignment Active</h3>
          <p className="text-sm font-medium text-gray-600 mt-1 max-w-4xl leading-relaxed">
            These logs are strictly mapped to Central Pollution Control Board equipment codes. 
            Exporting from this view generates a legally compliant schema acceptable for your mandatory CPCB quarterly returns.
          </p>
        </div>
        <div className="hidden lg:block border-l border-blue-200 pl-6 ml-2">
            <p className="text-2xl font-black text-gray-900">{totalWeight}<span className="text-xs font-bold text-gray-500 uppercase ml-1">kg</span></p>
            <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mt-0.5">Total Weight Logged</p>
        </div>
      </div>

      {/* Compliance Table */}
      <div className="bg-white rounded-3xl border border-gray-100 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead className="bg-gray-50/80 border-b border-gray-100">
              <tr>
                <th className="px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-widest">Entry Date</th>
                <th className="px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-widest">CPCB Code</th>
                <th className="px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-widest">Equipment Class</th>
                <th className="px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-widest">Qty</th>
                <th className="px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-widest">Weight (KG)</th>
                <th className="px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-widest">Compliance Status</th>
                <th className="px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-widest text-right">Form-2</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {logs.map((log) => (
                <tr key={log.id} className="hover:bg-gray-50/50 transition-colors group cursor-default">
                  <td className="px-6 py-5 text-sm font-semibold text-gray-600">{log.date}</td>
                  <td className="px-6 py-5">
                    <span className="inline-flex items-center px-2.5 py-1 rounded-lg text-xs font-black bg-slate-100 border border-slate-200 text-slate-700 tracking-widest group-hover:border-slate-300 transition-colors">
                      {log.code}
                    </span>
                  </td>
                  <td className="px-6 py-5 text-sm font-bold text-gray-800">{log.desc}</td>
                  <td className="px-6 py-5 text-sm font-black text-gray-900">{log.qty} <span className="text-xs text-gray-400 font-medium ml-1">units</span></td>
                  <td className="px-6 py-5 text-sm font-black text-emerald-700">{(log.weight ?? 0).toFixed(1)}</td>
                  <td className="px-6 py-5">
                    <span className={`inline-flex items-center px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-widest ${
                      log.status === "PROCESSED" ? "bg-emerald-50 text-emerald-700 border border-emerald-100" : "bg-amber-50 text-amber-700 border border-amber-100"
                    }`}>
                      {log.status}
                    </span>
                  </td>
                  <td className="px-6 py-5 text-right">
                    <button onClick={(e) => handleDownloadReceipt(e, log)} className="p-2 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded-xl transition-colors tooltip" title="Download Form-2 Receipt">
                      <Download size={18} />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    
    </div>
  );
}
